### ISSUE TITLE
Group member count incorrect

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#517]
**Describe the bug**
New groups are one member off. Not sure if it's not counting the admin, but this group has 3 members, but only lists 2: https://hcommons-staging.org/groups/daves-group-2023/members/

Old groups appear to be unaffected: https://hcommons-staging.org/groups/mesh/members/

**To Reproduce**
1. Join any group
2. Count is off

**Expected behavior**
The member count should match the number of members listed in the membership list. 

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [x] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by mikethicke** [comment]
```BP_Groups_Group::get_total_member_count()``` is the function responsible for calculating the number of group members. It excludes spammed, blocked, and inactive users. It queries for active members by querying the ```wp_bp_activity``` table for each user's last activity.

In the case of these groups, the bonnie user somehow has two last_activity records:

```
mysql> SELECT id,user_id,component,date_recorded FROM wp_bp_activity WHERE user_id IN (1015176,1049869,1049868) AND type = 'last_activity';
+---------+---------+-----------+---------------------+
| id      | user_id | component | date_recorded       |
+---------+---------+-----------+---------------------+
| 1615479 | 1015176 | members   | 2023-01-23 16:49:40 |
| 1766734 | 1015176 | members   | 2022-08-18 15:43:22 |
| 1785017 | 1049868 | members   | 2023-01-23 16:48:02 |
| 1785020 | 1049869 | members   | 2023-01-23 20:56:09 |
+---------+---------+-----------+---------------------+
```

(Bonnie has user_id 1015176)

Because of how the query is constructed, this ends up "pushing out" another user from the count and ultimately reducing the group count by 1.

The most relevant code is in ```BP_Core_User::get_last_activity()```:

```
                 $uncached_user_ids = bp_get_non_cached_ids( $user_ids, 'bp_last_activity' );
		if ( ! empty( $uncached_user_ids ) ) {
			$bp = buddypress();

			$user_ids_sql = implode( ',', $uncached_user_ids );
			$user_count   = count( $uncached_user_ids );

			$last_activities = $wpdb->get_results( $wpdb->prepare( "SELECT id, user_id, date_recorded FROM {$bp->members->table_name_last_activity} WHERE component = %s AND type = 'last_activity' AND user_id IN ({$user_ids_sql}) LIMIT {$user_count}", $bp->members->id ) );

			foreach ( $last_activities as $last_activity ) {
				$success = wp_cache_set( $last_activity->user_id, array(
					'user_id'       => $last_activity->user_id,
					'date_recorded' => $last_activity->date_recorded,
					'activity_id'   => $last_activity->id,
				), 'bp_last_activity' );
			}
		}

		// Fetch all user data from the cache.
		$retval = array();
		foreach ( $user_ids as $user_id ) {
			$retval[ $user_id ] = wp_cache_get( $user_id, 'bp_last_activity' );

			if ( isset( $retval['user_id'] ) ) {
				$retval[ $user_id ]['user_id']     = (int) $retval[ $user_id ]['user_id'];
			}
			if ( isset( $retval['activity_id'] ) ) {
				$retval[ $user_id ]['activity_id'] = (int) $retval[ $user_id ]['activity_id'];
			}
		}
```

In the upper stanza, the query has a LIMIT clause that limits results to 3. Because bonnie has 2 records, there would be 4 results from this query if the LIMIT clause wasn't there.

In the bottom stanza, the count is done by looking at which users had results come back from the previous query. Only 2 do, and so the count is 2 rather than 3.

This is all pretty deep in BuddyPress code and doesn't seem to be the result of any of our code interfering with the calculation.

It might be a quirk or our production-development sync process that caused bonnie to have multiple last_activity records.

As this is not a breaking issue, I'm closing and we can check if it occurs in production. If it does, the best first course of action is probably to run a script that de-duplicates last_activity records on the assumption that there was some one-time integrity failure with the database.
