### ISSUE TITLE
FSE theme templates and the block editor query loops are not working properly on staging

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#518]
**Describe the bug**
FSE templates aren't populating correctly, and the query loops and other template parts are not working either. I've tried with both Dave Test (hctester50) and Ferdinand Test (hctester40) and it does not appear to be a user issue. I've tried 2023 and Blockbase, and you can see an example on Blockbase here: https://davesgroup2023.hcommons-staging.org/blog/. 

Query loops are also not working on legacy themes like Twenty Twenty: https://ferdssite.hcommons-staging.org/blog/. It's as though something may not have fully installed? I've tried for three days and it happens every time with multiple users and themes. 

This works fine on production in both FSE and legacy themes. 

**To Reproduce**
1. Create a new page on a site
2. Add the query loop block and choose one (it's best to have a few blog posts, but one is enough)
3. The preview window works
4. Save the page and no contents show

If you try to create a new template to display blog posts in a FSE theme you can't add it to the page.
1. Create a new template
2. Try to add the template to a page
3. The template is not available to be picked

**Expected behavior**
Adding a query loop block in the block editor on either a legacy or FSE theme should allow you to display a list of all blog posts on the page, or by tag/category. 

When you create a new template in a FSE theme you should be able to apply that template when editing a page. 

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [x] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by mikethicke** [comment]
For query loops:

There is a toggle "Inherit query from template" in the query loop settings: 

![Screen Shot 2023-01-06 at 10.02.41 AM.png](https://images.zenhubusercontent.com/6108aeed64d7503f6ae51eff/8cc16860-3788-4ef6-a589-4ba07bafbe43)

If this is toggled to "on", and the loop isn't using a template that provides that context, such as the search template or archives template, then nothing will show up because the query doesn't run. Toggling this to off will make the query run. 

I'm not sure whether to classify this as a WordPress bug or just a stupid design choice, but it isn't something about our configuration that is messing things up.

**Comment by mikethicke** [comment]
@bjr70 --- Can you say more about what you mean by "FSE templates aren't populating correctly"? Is this a separate issue from the query loop issue? If I edit the single template it does seem to affect all existing posts.

**Comment by bjr70** [comment]
Yeah, let me look at the other issue again as it may be a 2023 issue and not a global issue. This issue is fixed and I'm closing. If there's another issue with templates I'll create a new ticket.
