### ISSUE TITLE
Move MSU Commons groups and site onto HCommons

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#563]
The admin of the STEM Ed PaCER would like their [site](https://stemedpacer.commons.msu.edu/) and two groups ([STEM Ed PaCER Meet the Mentors](https://commons.msu.edu/groups/stem-ed-pacer-meet-the-mentors/) and [STEM Ed PaCER Internal Project Workspace](https://commons.msu.edu/groups/stem-ed-pacer-postdoctoral-research-fellows/))  moved from MSU Commons to HCommons.

**Comment by mikethicke** [comment]
STEM Ed PaCER is now at https://stemedpacer.hcommons.org/
STEM Ed PaCER Meet The Mentors is now at https://stemedpacermeetthementors.hcommons.org/

The old commons.msu.edu URLs redirect to the new sites.

I created a script to change group type here: https://github.com/MESH-Research/dev-scripts/blob/master/commons/change-group-type.php

But that doesn't move the discussion forum or discussion posts, which breaks the group. This is a challenge because the discussions and discussion posts are in the MSU posts table and would need to be exported and then imported into the HC posts table, and then linked back up to the groups. Making this work correctly will take some significant work. If possible, it would be far quicker to just recreate the groups.
