### ISSUE TITLE
Create CSV for metrics 

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#695]
Please create a feed to pull the following metrics into a CSV file: 

**General:** 

- No. users total
- No. users active within last month (logged in)

**Groups:** 
- Total number of groups
- Average members per group
- Average deposits per group
- Average discussion posts per group
- No. groups with/without site

**Repository**

- Total deposits
- No. deposits tracked over time
- No. views per deposit
- No. downloads per deposit
- List of top deposits by download
- List of users with most deposits

**Sites:** 

- Total sites
- Average posts per site
- Average comments per site 

(Arranged in order of priority)

**Comment by bjr70** [comment]
Edited to add repository metrics. Mike - see me if some of these are not possible in the current database.

**Comment by zwhnz** [comment]
Edited to arrange in order of priority.

**Comment by mikethicke** [comment]
Sample CSV file attached.

[metrics-2023-08-23.csv.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDhxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7eab7be48c9d89ad05174cbf675afb9d67dedee9/metrics-2023-08-23.csv.zip)

Notes:

- There is one row in the CSV, as these are all summary statistics
- I haven't done the Repository section, as I believe those stats might be available elsewhere and I'd rather not duplicate work.
- Total users includes HASTAC users who have not logged in since the merger. I can exclude those if desired.
- I have also included user counts for each society
- The script takes quite a while to run as there are a lot of database queries required for some of these statistics (like counting comments for each blog)
- I don't think the summary statistics are particularly enlightening. You'd probably want something more like a histogram to glean anything useful there. The distributions are not even approximately normal.
- A "feed" would take considerable work to implement for security and performance reasons. The easier approach is to generate the CSV automatically every week or month and have it emailed to you. Presumably you'd then copy the row into an ongoing spreadsheet to see changes through time.

**Comment by mikethicke** [comment]
Script is here: https://github.com/MESH-Research/dev-scripts/blob/master/metrics/generate-metrics-csv.php

**Comment by mikethicke** [comment]
Initial CSV created. Will create new issue for revisions.
