### ISSUE TITLE
ARLIS/NA group won't load--reverts back to homepage

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#707]
**Describe the bug**
ARLIS/NA group won't load. Going to the URL--https://arlisna.hcommons.org/groups/arlis-na-reviews-authors/--or selecting it from the Groups directory leads back to the HCommons home page. 

**To Reproduce**
1. Go to '[https://arlisna.hcommons.org/groups/](https://arlisna.hcommons.org/groups/)'
2. Click on 'ARLIS/NA Reviews Authors'
3. Group reverts back to homepage

**Context**
Does this bug on production, development, or both?
- [ ] Tested on development instance
- [ ] Occurs on development instance
- [x] Tested on production
- [x] Occurs on productions

**Additional context**
A user reported an issue with docs--"I created a doc that is now saying "Awaiting Moderation" - this doc is not showing up in the group, only in my list of created docs." When I went to investigate, I had the above behavior occur. The user (who is also the group's admin) is reporting the same issue when she tried to access the group.

**Comment by mikethicke** [comment]
There's a couple of issues here. The main problem was that there was no discussion board associated with the group. When editing the group, there is a metabox on the right. It was like this:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0tDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--228b5d5d0c7207e17853c9413ecaaff55132d5ac/Screenshot%202023-09-08%20at%204.32.34%20PM.png)
 
Which was probably resulting in a 404 error and homepage redirect.

It should look like this:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ09DIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d22dd84f17078903e75493cfb700484c93f8ea2d/Screenshot%202023-09-08%20at%204.31.09%20PM.png)

That problem is corrected.

Second, the group is set to "Hidden". This is perhaps because it wasn't functioning? Regardless, if it is supposed to be accessible to all ARLIS/NA users, it needs to be set to public.

**Comment by bjr70** [comment]
@babaklar was this resolved?

**Comment by babaklar** [comment]
Emailed user.
