### ISSUE TITLE
HASTAC Commons plugin refresh interval error

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#732]
This was reported by Chris McGuinness from HASTAC for HASTAC Commons: 

"I'm writing in reference to https://hastac.hcommons.org.  The front page uses the plugin WP RSS Aggregator to display recent posts. However, it is not showing any posts from after July (for example, https://educational-cultural-institutions.hastac.hcommons.org/2023/09/20/welcome-hastac-scholars/). When I checked the settings, the refresh interval was set to 2 hours. However the last refresh mentioned was 2 months prior and also next scheduled in 2 months. I changed the interval to 15 minutes and the scheduled refresh started to count up. Is there a setting I do not understand? Or is the plugin malfunctioning?"

**Comment by mikethicke** [comment]
In a previous issue (which I can't find :-/) we had a daily problem with very slow page loads across the site that was traced to scheduled tasks with wp-cron. Wp-cron was configured to run once-per day rather than on each page load to address this issue. However, this seems to have been working incorrectly, or perhaps failing at some point before completion, and so the job that updated the RSS feeds was not firing.

The cron job has been updated and wp-cron has been run manually, which corrected the HASTAC issue.

If further cron issues are discovered I will create a separate issue.
