### ISSUE TITLE
ARLIS/NA deposits added to a group are not appearing in the group

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#840]
An ARLIS/NA group admin informed us that deposits added to the group are not appearing in the under the "From CORE" section. I'm pretty sure this is occurring because of the special characters in the group name--[we've encountered this issue before](https://app.zenhub.com/workspaces/hc-development-61143609f268f000196abf18/issues/gh/mesh-research/commons/743). The group is called [Multimedia & Technology Reviews Editors](https://arlisna.hcommons.org/groups/multimedia-technology-reviews-editors-63751863/deposits/).

Here is one of the deposits not appearing in the group (when you select the name of the group it goes to a blank page): [https://arlisna.hcommons.org/deposits/item/hc:59393/](https://arlisna.hcommons.org/deposits/item/hc:59393/)

**Comment by mikethicke** [comment]
The fix for MESH-Resarch/commons#743 was a bit overzealous in encoding special characters, which broke how the ampersand was being handled (as you suspected). https://github.com/MESH-Research/humcore/commit/ecbc30568b81c54ac9d10df93c59a515cd231ab0 rolls that partly back. Now both the ["Encoding Cultures" group](https://hcommons.org/deposits/?facets%5Bgroup_facet%5D%5B%5D=%22Encoding+Cultures%22+Joint+MEC+and+TEI+Conference) and the [Multimedia & Technology](https://arlisna.hcommons.org/deposits/?facets%5Bgroup_facet%5D%5B%5D=Multimedia+%26amp%3B+Technology+Reviews+Editors) are working.
