### ISSUE TITLE
fancy HTML email

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/commons#9]
Test wp-better-emails (https://wordpress.org/plugins/wp-better-emails/) and see if it can be cleanly integrated with BuddyPress, bbPress, our SMTP plugin, and the other elements of the email stack.

**Comment by JonathanReeve** [comment]
Discussion of a hook that allows HTML email: http://wordpress.stackexchange.com/a/27858/26588

**Comment by terrainsvagues** [comment]
Apparently "WP email goes to spam" (sez author of [dead plugin](https://wordpress.org/plugins/welcome-email-editor/))

"I would recommend the use of an SMTP service with any WordPress plugin. A large amount of emails fall needlessly into Spam bins across the world (I get a fair amount of comment approval spam to deal with) because the WordPress site uses Sendmail to deliver email. I noticed an immediate improvement when using SMTP to send. It's really easy so there's no excuse :)"

**Comment by chriszarate** [comment]
We already do that (which makes integrating other mail plugins tricky sometimes).

**Comment by chriszarate** [comment]
I did some work to offload mail delivery to the local mail daemon (`exim-ses` branch). This has a lot of advantages including better logging and queueing for resend when things go wrong (by default WordPress mail is just dropped when there's a problem). This also opens the door to using a plugin like WP-Better-Email as opposed to the all-HTML-or-nothing approach I discussed with Nicky. It's ready to deploy, but I'll need to keep an eye on it for a week or so to make sure it's working.

**Comment by modelm** [comment]
http://codecanyon.net/item/advanced-wordpress-email-delivery-/1290390?ref=wpexplorer&ref=wpexplorer&clickthrough_id=557462147&redirect_back=true

**Comment by terrainsvagues** [comment]
Upping the priority on this one.

**Comment by kfitz** [comment]
FYI, I'm going to forward around an example of the digest emails I get from NCTE's discussion boards. They use Higher Logic, and the emails look almost exactly like the site itself, which makes the idea of clicking and replying seem very straightforward.

**Comment by chriszarate** [comment]
Take a look at [Mailgun](http://www.mailgun.com/analytics) and similar services, which could allow us to track open rates automatically.
