### ISSUE TITLE
Blog posts on MLA site won't load

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#909]
**Describe the bug**
On the [MLA-CCCC JOINT TASK FORCE ON WRITING AND AI](https://aiandwriting.hcommons.org/) site, the blog posts don't load. Selecting a link goes to a blank page. 

**To Reproduce**
1. Go to [https://aiandwriting.hcommons.org/](https://aiandwriting.hcommons.org/)
2. Click on a blog post link in the right column
3. See white page with heading banner

**Expected behavior**

**Context**
Does this bug on production, development, or both?
- [ ] Tested on development instance
- [ ] Occurs on development instance
- [ ] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by mikethicke** [comment]
This was due to a typo in the Origin theme (an unquoted string @ /origin/library/extensions/breadcrumb-trail.php:1027). This type of error caused a warning in PHP 7.x but a hard crash in PHP 8.x. The theme had already been forked so I made a hotfix in the running container. A more permanent fix will be pushed in the next update.

We should get rid of this theme.
